# Generated by Django 4.1.13 on 2026-01-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=10, null=True),
        ),
    ]
