# Generated by Django 4.1.13 on 2026-01-26 16:12

from django.db import migrations
from core.utils import generate_url_id

def fill_url_id(apps, schema_editor):
    Post = apps.get_model('blog', 'Post')
    for post in Post.objects.all():
        while True:
            candidate = generate_url_id()
            if not Post.objects.filter(url_id=candidate).exists():
                post.url_id = candidate
                post.save(update_fields=['url_id'])
                break

def reverse_fill(apps, schema_editor):
    Post = apps.get_model('blog', 'Post')
    Post.objects.update(url_id=None)

class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0005_post_url_id'),
    ]

    operations = [
        migrations.RunPython(fill_url_id, reverse_fill),
    ]
