# Generated by Django 4.1.13 on 2026-01-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20260126_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url_id',
            field=models.CharField(db_index=True, editable=False, max_length=10, unique=True),
        ),
    ]
